; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 921600
monitor_dtr = 0
monitor_rts = 0
upload_speed = 460800
upload_flags =
	--after
	hard_reset
build_flags =
	-D CORE_DEBUG_LEVEL=0
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	h2zero/NimBLE-Arduino@^1.4.1

[env:nologo_esp32c3_super_mini]
platform = espressif32
board = nologo_esp32c3_super_mini
framework = arduino
monitor_speed = 921600
monitor_dtr = 0
monitor_rts = 0
upload_speed = 460800
upload_flags =
	--after
	hard_reset
build_flags =
	-D CORE_DEBUG_LEVEL=0
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	h2zero/NimBLE-Arduino@^1.4.1

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600
build_flags =
	-D CORE_DEBUG_LEVEL=0
lib_deps =
	h2zero/NimBLE-Arduino@^1.4.1
